# Cloudflare Pages configuration
name = "stockx-consignment-portal"
compatibility_date = "2024-04-10"
workers_dev = true

# Bind a KV namespace for token storage
kv_namespaces = [
  { binding = "TOKEN_STORE", id = "4ada3e43a5194e89a246f1c368ced458" }
]

# Build settings
[build]
command = "npm run build"

# Pages configuration
site = { bucket = "public" }

# Environment variables
[vars]
NODE_ENV = "production"
STOCKX_CLIENT_ID = "KlbEZjymb9OBap9a3jWlX9bIx4j4y3ks"
STOCKX_CLIENT_SECRET = "y2GqspIoDSgzoryXS3Ue--5i0xlXQUU09F4cqnuVgn6Szk4efqZy1qGip_EVqmqe"
REDIRECT_URI = "https://stockx-consignment-portal.pages.dev/callback"
STOCKX_API_KEY = "OEgPz70FHNL5AxwwK8fJ92Uyk18knTDOdTBxPmi0"

# Set up cron triggers for background token refresh
[triggers]
crons = ["*/10 * * * *"] # Run every 10 minutes