# Cloudflare Pages configuration
name = "stockx-consignment-portal"
compatibility_date = "2023-10-30"
workers_dev = true

# Bind a KV namespace for token storage
kv_namespaces = [
  { binding = "TOKEN_STORE", id = "4ada3e43a5194e89a246f1c368ced458" }
]

# Build settings
[build]
command = "npm run build"
output_dir = "out"

# Pages configuration
pages_build_output_dir = "out"
compatibility_date = "2024-04-10"

[functions]
directory = "functions"

# Environment variables
[vars]
NODE_ENV = "production"

# Set up cron triggers for background token refresh
[triggers]
crons = ["*/10 * * * *"] # Run every 10 minutes

# Set up routes
[[routes]]
pattern = "/*"
script = "index.js"

# Preview environments
[env.preview]
workers_dev = true

# Production environment
[env.production]
workers_dev = false
route = "consignment.example.com/*"


